// ShadowGrid AI — AI (Gemini) zone insight panel
//
// On demand, sends the zone's structured risk data to the LLM explanation
// Edge Function and renders a plain-language explanation + recommended action.
// Falls back silently (renders nothing actionable) when AI is not configured.

import { useState } from 'react';
import { Sparkles, Loader2, AlertCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useAppStore } from '@/store/AppContext';
import { AI_ENABLED } from '@/lib/appConfig';
import { explainZoneRisk, type AiZoneExplanation } from '@/services/aiService';
import type { Zone } from '@/types/types';

interface AiZoneInsightProps {
  zone: Zone;
}

export function AiZoneInsight({ zone }: AiZoneInsightProps) {
  const {
    getZoneSummary, getRiskScoresForZone, getExplanationForZone,
    externalSignals, citizenReports,
  } = useAppStore();

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AiZoneExplanation | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!AI_ENABLED) return null;

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    try {
      const res = await explainZoneRisk({
        zone,
        summary: getZoneSummary(zone.id),
        scores: getRiskScoresForZone(zone.id),
        signals: externalSignals.filter(s => s.zone_id === zone.id),
        reports: citizenReports.filter(r => r.zone_id === zone.id),
        propagation: getExplanationForZone(zone.id)?.propagationNote ?? undefined,
      });
      if (res) setResult(res);
      else setError('AI explanation unavailable right now. Showing engine analysis above.');
    } catch {
      setError('AI explanation failed. Showing engine analysis above.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="border-primary/30 bg-primary/[0.03]">
      <CardContent className="p-4 space-y-3">
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-2">
            <Sparkles size={15} className="text-primary" />
            <span className="text-sm font-semibold text-foreground">AI Insight</span>
            <Badge variant="outline" className="text-[10px] h-5 bg-primary/10 text-primary border-primary/30">
              Gemini
            </Badge>
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="gap-1.5 text-xs border border-primary/40 text-primary hover:bg-primary/10"
            onClick={handleGenerate}
            disabled={loading}
          >
            {loading ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
            {loading ? 'Generating…' : result ? 'Regenerate' : 'Explain with AI'}
          </Button>
        </div>

        {!result && !error && !loading && (
          <p className="text-xs text-muted-foreground text-pretty">
            Generate a plain-language summary of why this zone is at risk and the recommended first action,
            powered by an LLM over the live risk data.
          </p>
        )}

        {error && (
          <div className="flex items-start gap-2 text-xs text-yellow-400">
            <AlertCircle size={13} className="mt-0.5 shrink-0" />
            <span className="text-pretty">{error}</span>
          </div>
        )}

        {result && (
          <div className="space-y-3">
            <p className="text-sm text-foreground text-pretty leading-relaxed">{result.explanation}</p>
            <div className="p-3 rounded-lg bg-primary/8 border border-primary/20">
              <p className="text-xs font-medium text-primary mb-1">Recommended action</p>
              <p className="text-sm text-muted-foreground text-pretty">{result.action}</p>
            </div>
            <p className="text-[10px] text-muted-foreground/70">
              Generated by {result.model}. AI output may be imperfect — verify against the engine analysis.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
